/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [https://neo4j.com]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.neo4j.cypher.internal.parser.v5;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Map;
import org.antlr.v4.runtime.ParserRuleContext;

/**
 * Optimised implementation of Cypher5ParserListener.
 * Generated by org.neo4j.cypher.internal.parser.GenerateListenerMavenPlugin
 */
public abstract class AbstractCypher5AstBuilder implements Cypher5ParserListener {
    private static final Map<String, Method> EXIT_METHODS = buildExitMethodMap();
    private final Method[] exitMethodsByRule = buildExitMethodsByRule();

    /**
     *
     * Optimised exit method.
     *
     * Dispatches parser rules to the corresponding exit* listener method
     * based on the current generated rule set.
     */
    @Override
    public final void exitEveryRule(ParserRuleContext ctx) {
        int ruleIndex = ctx.getRuleIndex();
        if (ruleIndex < 0 || ruleIndex >= exitMethodsByRule.length) {
            throw new IllegalStateException("Unknown rule index " + ruleIndex);
        }
        Method method = exitMethodsByRule[ruleIndex];
        if (method == null) {
            String ruleName = Cypher5Parser.ruleNames[ruleIndex];
            throw new IllegalStateException("Missing exit listener method for rule " + ruleName);
        }
        try {
            method.invoke(this, ctx);
        } catch (IllegalAccessException | InvocationTargetException e) {
            String ruleName = Cypher5Parser.ruleNames[ruleIndex];
            throw new IllegalStateException("Failed to invoke exit method for rule " + ruleName, e);
        }
    }

    private static Map<String, Method> buildExitMethodMap() {
        Map<String, Method> methods = new HashMap<>();
        for (Method method : Cypher5ParserListener.class.getMethods()) {
            if (method.getName().startsWith("exit") && method.getParameterCount() == 1) {
                methods.put(method.getName(), method);
            }
        }
        return methods;
    }

    private Method[] buildExitMethodsByRule() {
        Method[] methods = new Method[Cypher5Parser.ruleNames.length];
        for (int i = 0; i < Cypher5Parser.ruleNames.length; i++) {
            String ruleName = Cypher5Parser.ruleNames[i];
            String methodName = "exit" + Character.toUpperCase(ruleName.charAt(0)) + ruleName.substring(1);
            methods[i] = EXIT_METHODS.get(methodName);
        }
        return methods;
    }
}
