/* CypherPreParserTokenManager.java */
/* Generated by: ParserGeneratorCC: Do not edit this line. CypherPreParserTokenManager.java */
/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [https://neo4j.com]
 *
 * This file is part of Neo4j.
 *
 * Neo4j is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.neo4j.cypher.internal.preparser.javacc;
import org.neo4j.cypher.internal.PreParsedStatement;
import org.neo4j.cypher.internal.PreParserOption;
import org.neo4j.cypher.internal.parser.common.ast.factory.ASTExceptionFactory;
import org.neo4j.cypher.internal.parser.common.InvalidUnicodeLiteral;
import org.neo4j.cypher.internal.util.InputPosition;
import java.util.ArrayList;
import java.util.List;
import org.neo4j.gqlstatus.GqlHelper;

/** Token Manager. */
@SuppressWarnings ("unused")
public class CypherPreParserTokenManager implements CypherPreParserConstants {
 public void CommonTokenAction(Token t)
 {
     PreParserCharStream ccStream = (PreParserCharStream)input_stream;
  t.beginOffset = ccStream.getBeginOffset();
  t.endOffset = ccStream.getEndOffset();
 }
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case '/':
         jjmatchedKind = 7;
         return jjMoveStringLiteralDfa1_0(0x400L);
      case '=':
         jjmatchedKind = 6;
         return jjMoveNfa_0(1, 0);
      case 'C':
         return jjMoveStringLiteralDfa1_0(0x8L);
      case 'E':
         return jjMoveStringLiteralDfa1_0(0x2L);
      case 'P':
         return jjMoveStringLiteralDfa1_0(0x4L);
      case 'c':
         return jjMoveStringLiteralDfa1_0(0x8L);
      case 'e':
         return jjMoveStringLiteralDfa1_0(0x2L);
      case 'p':
         return jjMoveStringLiteralDfa1_0(0x4L);
      default :
         return jjMoveNfa_0(1, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 0);
   }
   switch(curChar)
   {
      case '*':
         if ((active0 & 0x400L) != 0x0L)
         {
            jjmatchedKind = 10;
            jjmatchedPos = 1;
         }
         break;
      case 'R':
         return jjMoveStringLiteralDfa2_0(active0, 0x4L);
      case 'X':
         return jjMoveStringLiteralDfa2_0(active0, 0x2L);
      case 'Y':
         return jjMoveStringLiteralDfa2_0(active0, 0x8L);
      case 'r':
         return jjMoveStringLiteralDfa2_0(active0, 0x4L);
      case 'x':
         return jjMoveStringLiteralDfa2_0(active0, 0x2L);
      case 'y':
         return jjMoveStringLiteralDfa2_0(active0, 0x8L);
      default :
         break;
   }
   return jjMoveNfa_0(1, 1);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 1);
   }
   switch(curChar)
   {
      case 'O':
         return jjMoveStringLiteralDfa3_0(active0, 0x4L);
      case 'P':
         return jjMoveStringLiteralDfa3_0(active0, 0xaL);
      case 'o':
         return jjMoveStringLiteralDfa3_0(active0, 0x4L);
      case 'p':
         return jjMoveStringLiteralDfa3_0(active0, 0xaL);
      default :
         break;
   }
   return jjMoveNfa_0(1, 2);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 2);
   }
   switch(curChar)
   {
      case 'F':
         return jjMoveStringLiteralDfa4_0(active0, 0x4L);
      case 'H':
         return jjMoveStringLiteralDfa4_0(active0, 0x8L);
      case 'L':
         return jjMoveStringLiteralDfa4_0(active0, 0x2L);
      case 'f':
         return jjMoveStringLiteralDfa4_0(active0, 0x4L);
      case 'h':
         return jjMoveStringLiteralDfa4_0(active0, 0x8L);
      case 'l':
         return jjMoveStringLiteralDfa4_0(active0, 0x2L);
      default :
         break;
   }
   return jjMoveNfa_0(1, 3);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 3);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 3);
   }
   switch(curChar)
   {
      case 'A':
         return jjMoveStringLiteralDfa5_0(active0, 0x2L);
      case 'E':
         return jjMoveStringLiteralDfa5_0(active0, 0x8L);
      case 'I':
         return jjMoveStringLiteralDfa5_0(active0, 0x4L);
      case 'a':
         return jjMoveStringLiteralDfa5_0(active0, 0x2L);
      case 'e':
         return jjMoveStringLiteralDfa5_0(active0, 0x8L);
      case 'i':
         return jjMoveStringLiteralDfa5_0(active0, 0x4L);
      default :
         break;
   }
   return jjMoveNfa_0(1, 4);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 4);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 4);
   }
   switch(curChar)
   {
      case 'I':
         return jjMoveStringLiteralDfa6_0(active0, 0x2L);
      case 'L':
         return jjMoveStringLiteralDfa6_0(active0, 0x4L);
      case 'R':
         if ((active0 & 0x8L) != 0x0L)
         {
            jjmatchedKind = 3;
            jjmatchedPos = 5;
         }
         break;
      case 'i':
         return jjMoveStringLiteralDfa6_0(active0, 0x2L);
      case 'l':
         return jjMoveStringLiteralDfa6_0(active0, 0x4L);
      case 'r':
         if ((active0 & 0x8L) != 0x0L)
         {
            jjmatchedKind = 3;
            jjmatchedPos = 5;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(1, 5);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjMoveNfa_0(1, 5);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_0(1, 5);
   }
   switch(curChar)
   {
      case 'E':
         if ((active0 & 0x4L) != 0x0L)
         {
            jjmatchedKind = 2;
            jjmatchedPos = 6;
         }
         break;
      case 'N':
         if ((active0 & 0x2L) != 0x0L)
         {
            jjmatchedKind = 1;
            jjmatchedPos = 6;
         }
         break;
      case 'e':
         if ((active0 & 0x4L) != 0x0L)
         {
            jjmatchedKind = 2;
            jjmatchedPos = 6;
         }
         break;
      case 'n':
         if ((active0 & 0x2L) != 0x0L)
         {
            jjmatchedKind = 1;
            jjmatchedPos = 6;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_0(1, 6);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec3 = {
   0xfff0000040220002L, 0xffffffffffffdfffL, 0xfffff02f7fffffffL, 0x12000000007fffffL
};
static final long[] jjbitVec4 = {
   0x20000000L, 0x2000L, 0x0L, 0x0L
};
static final long[] jjbitVec5 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0x0L
};
static final long[] jjbitVec6 = {
   0x0L, 0x0L, 0x420043c00000000L, 0xff7fffffff7fffffL
};
static final long[] jjbitVec7 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0x501f0003ffc3L
};
static final long[] jjbitVec8 = {
   0x0L, 0xbcdf000000000000L, 0xfffffffbffffd740L, 0xffbfffffffffffffL
};
static final long[] jjbitVec9 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xfffffffffffffc03L, 0xffffffffffffffffL
};
static final long[] jjbitVec10 = {
   0xfffeffffffffffffL, 0xffffffff027fffffL, 0x81ffL, 0x787ffffff0000L
};
static final long[] jjbitVec11 = {
   0xffffffff00000800L, 0xfffec000000007ffL, 0xffffffffffffffffL, 0x9c00c060002fffffL
};
static final long[] jjbitVec12 = {
   0xfffffffd0000L, 0xffffffffffffe000L, 0x2003fffffffffL, 0xc43007fffffffc00L
};
static final long[] jjbitVec13 = {
   0x110043fffffL, 0x7ff01ffffffL, 0xffdfffff00000000L, 0xffL
};
static final long[] jjbitVec14 = {
   0x23fffffffffffff0L, 0xfffe0003ff010000L, 0x23c5fdfffff99fe1L, 0x180f0003b0004000L
};
static final long[] jjbitVec15 = {
   0x36dfdfffff987e0L, 0x1c00005e000000L, 0x23edfdfffffbbfe0L, 0x202000300010000L
};
static final long[] jjbitVec16 = {
   0x23edfdfffff99fe0L, 0x20003b0000000L, 0x3ffc718d63dc7e8L, 0x200000000010000L
};
static final long[] jjbitVec17 = {
   0x23fffdfffffddfe0L, 0x307000000L, 0x23effdfffffddfe1L, 0x6000340000000L
};
static final long[] jjbitVec18 = {
   0x27fffffffffddff0L, 0xfc00000380704000L, 0x2ffbfffffc7fffe0L, 0x7fL
};
static final long[] jjbitVec19 = {
   0x800dfffffffffffeL, 0x7fL, 0x200dffaffffff7d6L, 0xf000005fL
};
static final long[] jjbitVec20 = {
   0x1L, 0x1ffffffffeffL, 0x1f00L, 0x0L
};
static final long[] jjbitVec21 = {
   0x800007ffffffffffL, 0xffe1c0623c3f0000L, 0xffffffff00004003L, 0xf7ffffffffff20bfL
};
static final long[] jjbitVec22 = {
   0xffffffffffffffffL, 0xffffffff3d7f3dffL, 0x7f3dffffffff3dffL, 0xffffffffff7fff3dL
};
static final long[] jjbitVec23 = {
   0xffffffffff3dffffL, 0x7ffffffL, 0xffffffff0000ffffL, 0x3f3fffffffffffffL
};
static final long[] jjbitVec24 = {
   0xffffffffffffffffL, 0xffff9fffffffffffL, 0xffffffff07fffffeL, 0x1ffc7ffffffffffL
};
static final long[] jjbitVec25 = {
   0x3ffff0003dfffL, 0x1dfff0003ffffL, 0xfffffffffffffL, 0x18800000L
};
static final long[] jjbitVec26 = {
   0xffffffff00000000L, 0x1ffffffffffffffL, 0xffff05ffffffff9fL, 0x3fffffffffffffL
};
static final long[] jjbitVec27 = {
   0x7fffffffL, 0x1f3fffffff0000L, 0xffff0fffffffffffL, 0x3ffL
};
static final long[] jjbitVec28 = {
   0xffffffff007fffffL, 0x1fffffL, 0x8000000000L, 0x0L
};
static final long[] jjbitVec29 = {
   0xfffffffffffe0L, 0xfe0L, 0xfc00c001fffffff8L, 0x3fffffffffL
};
static final long[] jjbitVec30 = {
   0xfffffffffL, 0x3ffffffffc00e000L, 0xe7ffffffffff01ffL, 0x46fde0000000000L
};
static final long[] jjbitVec31 = {
   0xffffffff3f3fffffL, 0x3fffffffaaff3f3fL, 0x5fdfffffffffffffL, 0x1fdc1fff0fcf1fdcL
};
static final long[] jjbitVec32 = {
   0x8000000000000000L, 0x8002000000100001L, 0xffffffff1fff0000L, 0x0L
};
static final long[] jjbitVec33 = {
   0xf3ffbd503e2ffc84L, 0xffffffff000043e0L, 0x1ffL, 0x0L
};
static final long[] jjbitVec34 = {
   0xffff7fffffffffffL, 0xffffffff7fffffffL, 0xffffffffffffffffL, 0xc781fffffffffL
};
static final long[] jjbitVec35 = {
   0xffff20bfffffffffL, 0x80ffffffffffL, 0x7f7f7f7f007fffffL, 0x7f7f7f7fL
};
static final long[] jjbitVec36 = {
   0x800000000000L, 0x0L, 0x0L, 0x0L
};
static final long[] jjbitVec37 = {
   0x1f3e03fe000000e0L, 0xfffffffffffffffeL, 0xfffffffee07fffffL, 0xf7ffffffffffffffL
};
static final long[] jjbitVec38 = {
   0xfffeffffffffffe0L, 0xffffffffffffffffL, 0xffffffff00007fffL, 0xffff000000000000L
};
static final long[] jjbitVec39 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0x1fffffffffffffffL
};
static final long[] jjbitVec40 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0x1fffL, 0x3fffffffffff0000L
};
static final long[] jjbitVec41 = {
   0xc00ffff1fffL, 0x80007fffffffffffL, 0xffffffff3fffffffL, 0xffffffffffffL
};
static final long[] jjbitVec42 = {
   0xfffffffcff800000L, 0xffffffffffffffffL, 0xfffffffffffff9ffL, 0xffe00000000007fcL
};
static final long[] jjbitVec43 = {
   0x1000007fffff7bbL, 0xfffffffffffffL, 0xffffffffffffcL, 0x68fc000000000000L
};
static final long[] jjbitVec44 = {
   0xffff003ffffffc00L, 0x1fffffff0000007fL, 0x7fffffffffff0L, 0x7c00ffdf00008000L
};
static final long[] jjbitVec45 = {
   0x1ffffffffffL, 0xc47fffff00000ff7L, 0x3e62ffffffffffffL, 0x1c07ff38000005L
};
static final long[] jjbitVec46 = {
   0xffff7f7f007e7e7eL, 0xffff03fff7ffffffL, 0xffffffffffffffffL, 0x7ffffffffL
};
static final long[] jjbitVec47 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xffff000fffffffffL, 0xffffffffffff87fL
};
static final long[] jjbitVec48 = {
   0xffffffffffffffffL, 0xffff3fffffffffffL, 0xffffffffffffffffL, 0x3ffffffL
};
static final long[] jjbitVec49 = {
   0x5f7ffdffa0f8007fL, 0xffffffffffffffdbL, 0x3ffffffffffffL, 0xfffffffffff80000L
};
static final long[] jjbitVec50 = {
   0x3fffffffffffffffL, 0xffffffffffff0000L, 0xfffffffffffcffffL, 0x1fff0000000000ffL
};
static final long[] jjbitVec51 = {
   0x18000000000000L, 0xffdf02000000e000L, 0xffffffffffffffffL, 0x1fffffffffffffffL
};
static final long[] jjbitVec52 = {
   0x87fffffe00000010L, 0xffffffc007fffffeL, 0x7fffffffffffffffL, 0x631cfcfcfcL
};
static final long[] jjbitVec53 = {
   0x0L, 0x0L, 0x420243cffffffffL, 0xff7fffffff7fffffL
};
static final long[] jjbitVec54 = {
   0xffffffffffffffffL, 0xbcdfffffffffffffL, 0xfffffffbffffd740L, 0xffbfffffffffffffL
};
static final long[] jjbitVec55 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xfffffffffffffcfbL, 0xffffffffffffffffL
};
static final long[] jjbitVec56 = {
   0xfffeffffffffffffL, 0xffffffff027fffffL, 0xbffffffffffe81ffL, 0x787ffffff00b6L
};
static final long[] jjbitVec57 = {
   0xffffffff17ff083fL, 0xffffc3ffffffffffL, 0xffffffffffffffffL, 0x9ffffdffbfefffffL
};
static final long[] jjbitVec58 = {
   0xffffffffffff8000L, 0xffffffffffffe7ffL, 0x3ffffffffffffL, 0xe43fffffffffffffL
};
static final long[] jjbitVec59 = {
   0x3fffffffffffL, 0x7ff0fffffffL, 0xffdfffff00000000L, 0xfffffffffff800ffL
};
static final long[] jjbitVec60 = {
   0xffffffffffffffffL, 0xfffeffcfffffffffL, 0xf3c5fdfffff99fefL, 0x580fffcfb080799fL
};
static final long[] jjbitVec61 = {
   0xd36dfdfffff987eeL, 0x3fffc05e023987L, 0xf3edfdfffffbbfeeL, 0xfe02ffcf00013bbfL
};
static final long[] jjbitVec62 = {
   0xf3edfdfffff99feeL, 0x2ffcfb0e0399fL, 0xc3ffc718d63dc7ecL, 0x200ffc000813dc7L
};
static final long[] jjbitVec63 = {
   0xe3fffdfffffddfffL, 0xffcf07603ddfL, 0xf3effdfffffddfefL, 0x6ffcf40603ddfL
};
static final long[] jjbitVec64 = {
   0xfffffffffffddfffL, 0xfc00ffcf80f07ddfL, 0x2ffbfffffc7fffeeL, 0xcffc0ff5f847fL
};
static final long[] jjbitVec65 = {
   0x87fffffffffffffeL, 0x3ff7fffL, 0x3fffffaffffff7d6L, 0xf3ff3f5fL
};
static final long[] jjbitVec66 = {
   0xc2a003ff03000001L, 0xfffe1ffffffffeffL, 0x1ffffffffeffffdfL, 0x40L
};
static final long[] jjbitVec67 = {
   0xffffffffffffffffL, 0xffffffffffff03ffL, 0xffffffff3fffffffL, 0xf7ffffffffff20bfL
};
static final long[] jjbitVec68 = {
   0xffffffffff3dffffL, 0xe7ffffffL, 0xffffffff0000ffffL, 0x3f3fffffffffffffL
};
static final long[] jjbitVec69 = {
   0x1fffff001fdfffL, 0xddfff000fffffL, 0xffffffffffffffffL, 0x3ff388fffffL
};
static final long[] jjbitVec70 = {
   0xffffffff03ff7800L, 0x1ffffffffffffffL, 0xffff07ffffffffffL, 0x3fffffffffffffL
};
static final long[] jjbitVec71 = {
   0xfff0fff7fffffffL, 0x1f3fffffffffc0L, 0xffff0fffffffffffL, 0x3ff03ffL
};
static final long[] jjbitVec72 = {
   0xffffffff0fffffffL, 0x9fffffff7fffffffL, 0xbfff008003ff03ffL, 0x1L
};
static final long[] jjbitVec73 = {
   0xffffffffffffffffL, 0xff80003ff0fffL, 0xffffffffffffffffL, 0xfffffffffffffL
};
static final long[] jjbitVec74 = {
   0xffffffffffffffL, 0x3fffffffffffe3ffL, 0xe7ffffffffff01ffL, 0x7fffffffff70000L
};
static final long[] jjbitVec75 = {
   0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xfbffffffffffffffL
};
static final long[] jjbitVec76 = {
   0x80007c000000f800L, 0x8002ffdf00100001L, 0xffffffff1fff0000L, 0x1ffe21fff0000L
};
static final long[] jjbitVec77 = {
   0xffff7fffffffffffL, 0xffffffff7fffffffL, 0xffffffffffffffffL, 0xff81fffffffffL
};
static final long[] jjbitVec78 = {
   0xffff20bfffffffffL, 0x800080ffffffffffL, 0x7f7f7f7f007fffffL, 0xffffffff7f7f7f7fL
};
static final long[] jjbitVec79 = {
   0x1f3efffe000000e0L, 0xfffffffffffffffeL, 0xfffffffee67fffffL, 0xf7ffffffffffffffL
};
static final long[] jjbitVec80 = {
   0xfffffff1fffL, 0xbff0ffffffffffffL, 0xffffffffffffffffL, 0x3ffffffffffffL
};
static final long[] jjbitVec81 = {
   0x10010ffffffffffL, 0xfffffffffffffL, 0xffffffffffffffffL, 0xe8ffffff03ff003fL
};
static final long[] jjbitVec82 = {
   0xffff3fffffffffffL, 0x1fffffff000fffffL, 0xffffffffffffffffL, 0x7fffffff03ff8001L
};
static final long[] jjbitVec83 = {
   0x7fffffffffffffL, 0xfc7fffff03ff3fffL, 0xffffffffffffffffL, 0x7cffff38000007L
};
static final long[] jjbitVec84 = {
   0xffff7f7f007e7e7eL, 0xffff03fff7ffffffL, 0xffffffffffffffffL, 0x3ff37ffffffffffL
};
static final long[] jjbitVec85 = {
   0x5f7ffdffe0f8007fL, 0xffffffffffffffdbL, 0x3ffffffffffffL, 0xfffffffffff80000L
};
static final long[] jjbitVec86 = {
   0x18ffff0000ffffL, 0xffdf02000000e000L, 0xffffffffffffffffL, 0x9fffffffffffffffL
};
static final long[] jjbitVec87 = {
   0x87fffffe03ff0010L, 0xffffffc007fffffeL, 0x7fffffffffffffffL, 0xe0000631cfcfcfcL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int strKind = jjmatchedKind;
   int strPos = jjmatchedPos;
   int seenUpto;
   input_stream.backup(seenUpto = curPos + 1);
   try { curChar = input_stream.readChar(); }
   catch(final java.io.IOException e) { throw new Error("Internal Error"); }
   curPos = 0;
   int startsAt = 0;
   jjnewStateCnt = 12;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0xdc007ffeffffd9ffL & l) != 0x0L)
                  {
                     if (kind > 16)
                        kind = 16;
                     { jjCheckNAdd(11); }
                  }
                  else if ((0x3ff000000000000L & l) != 0x0L)
                  {
                     if (kind > 5)
                        kind = 5;
                  }
                  else if ((0x100002600L & l) != 0x0L)
                  {
                     if (kind > 8)
                        kind = 8;
                     { jjCheckNAdd(2); }
                  }
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 3;
                  if ((0x3ff400000000000L & l) != 0x0L)
                  {
                     if (kind > 4)
                        kind = 4;
                     { jjCheckNAdd(0); }
                  }
                  break;
               case 0:
                  if ((0x3ff400000000000L & l) == 0x0L)
                     break;
                  if (kind > 4)
                     kind = 4;
                  { jjCheckNAdd(0); }
                  break;
               case 2:
                  if ((0x100002600L & l) == 0x0L)
                     break;
                  if (kind > 8)
                     kind = 8;
                  { jjCheckNAdd(2); }
                  break;
               case 3:
                  if (curChar != 47)
                     break;
                  if (kind > 9)
                     kind = 9;
                  { jjCheckNAddStates(0, 2); }
                  break;
               case 4:
                  if ((0xffffffffffffdbffL & l) == 0x0L)
                     break;
                  if (kind > 9)
                     kind = 9;
                  { jjCheckNAddStates(0, 2); }
                  break;
               case 5:
                  if ((0x2400L & l) != 0x0L && kind > 9)
                     kind = 9;
                  break;
               case 6:
                  if (curChar == 10 && kind > 9)
                     kind = 9;
                  break;
               case 7:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 6;
                  break;
               case 8:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 10:
                  if ((0x3ff00100fffc1ffL & l) == 0x0L)
                     break;
                  if (kind > 13)
                     kind = 13;
                  jjstateSet[jjnewStateCnt++] = 10;
                  break;
               case 11:
                  if ((0xdc007ffeffffd9ffL & l) == 0x0L)
                     break;
                  if (kind > 16)
                     kind = 16;
                  { jjCheckNAdd(11); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if (kind > 16)
                     kind = 16;
                  { jjCheckNAdd(11); }
                  if ((0x7fffffe87fffffeL & l) != 0x0L)
                  {
                     if (kind > 13)
                        kind = 13;
                     { jjCheckNAdd(10); }
                  }
                  break;
               case 4:
                  if (kind > 9)
                     kind = 9;
                  { jjAddStates(0, 2); }
                  break;
               case 9:
                  if ((0x7fffffe87fffffeL & l) == 0x0L)
                     break;
                  if (kind > 13)
                     kind = 13;
                  { jjCheckNAdd(10); }
                  break;
               case 10:
                  if ((0x87fffffe87fffffeL & l) == 0x0L)
                     break;
                  if (kind > 13)
                     kind = 13;
                  { jjCheckNAdd(10); }
                  break;
               case 11:
                  if (kind > 16)
                     kind = 16;
                  { jjCheckNAdd(11); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if (jjCanMove_1(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 13)
                        kind = 13;
                     { jjCheckNAdd(10); }
                  }
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                  {
                     if (kind > 16)
                        kind = 16;
                     { jjCheckNAdd(11); }
                  }
                  break;
               case 4:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 9)
                     kind = 9;
                  { jjAddStates(0, 2); }
                  break;
               case 9:
                  if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 13)
                     kind = 13;
                  { jjCheckNAdd(10); }
                  break;
               case 10:
                  if (!jjCanMove_2(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 13)
                     kind = 13;
                  { jjCheckNAdd(10); }
                  break;
               case 11:
                  if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                     break;
                  if (kind > 16)
                     kind = 16;
                  { jjCheckNAdd(11); }
                  break;
               default : if (i1 == 0 || l1 == 0 || i2 == 0 ||  l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      i = jjnewStateCnt;
      jjnewStateCnt = startsAt;
      startsAt = 12 - jjnewStateCnt;
      if (i == startsAt)
         break;
      try { curChar = input_stream.readChar(); }
      catch(final java.io.IOException e) { break; }
   }
   if (jjmatchedPos > strPos)
      return curPos;

   int toRet = Math.max(curPos, seenUpto);

   if (curPos < toRet)
      for (i = toRet - Math.min(curPos, seenUpto); i-- > 0; )
         try { curChar = input_stream.readChar(); }
         catch(final java.io.IOException e) { throw new Error("Internal Error : Please send a bug report."); }

   if (jjmatchedPos < strPos)
   {
      jjmatchedKind = strKind;
      jjmatchedPos = strPos;
   }
   else
   if (jjmatchedPos == strPos && jjmatchedKind > strKind)
      jjmatchedKind = strKind;

   return toRet;
}
private int jjMoveStringLiteralDfa0_1(){
   switch(curChar)
   {
      case '*':
         return jjMoveStringLiteralDfa1_1(0x800L);
      case '/':
         return jjMoveStringLiteralDfa1_1(0x400L);
      default :
         return 1;
   }
}
private int jjMoveStringLiteralDfa1_1(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case '*':
         if ((active0 & 0x400L) != 0x0L)
            return jjStopAtPos(1, 10);
         break;
      case '/':
         if ((active0 & 0x800L) != 0x0L)
            return jjStopAtPos(1, 11);
         break;
      default :
         return 2;
   }
   return 2;
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, "\75", "\57", null, null, null, null, null, 
null, null, null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = im == null ? input_stream.getImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   t.image = curTokenImage;

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}
static final int[] jjnextStates = {
   4, 5, 7, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}
private static final boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec6[i2] & l2) != 0L);
      case 2:
         return ((jjbitVec7[i2] & l2) != 0L);
      case 3:
         return ((jjbitVec8[i2] & l2) != 0L);
      case 4:
         return ((jjbitVec9[i2] & l2) != 0L);
      case 5:
         return ((jjbitVec10[i2] & l2) != 0L);
      case 6:
         return ((jjbitVec11[i2] & l2) != 0L);
      case 7:
         return ((jjbitVec12[i2] & l2) != 0L);
      case 8:
         return ((jjbitVec13[i2] & l2) != 0L);
      case 9:
         return ((jjbitVec14[i2] & l2) != 0L);
      case 10:
         return ((jjbitVec15[i2] & l2) != 0L);
      case 11:
         return ((jjbitVec16[i2] & l2) != 0L);
      case 12:
         return ((jjbitVec17[i2] & l2) != 0L);
      case 13:
         return ((jjbitVec18[i2] & l2) != 0L);
      case 14:
         return ((jjbitVec19[i2] & l2) != 0L);
      case 15:
         return ((jjbitVec20[i2] & l2) != 0L);
      case 16:
         return ((jjbitVec21[i2] & l2) != 0L);
      case 18:
         return ((jjbitVec22[i2] & l2) != 0L);
      case 19:
         return ((jjbitVec23[i2] & l2) != 0L);
      case 20:
         return ((jjbitVec0[i2] & l2) != 0L);
      case 22:
         return ((jjbitVec24[i2] & l2) != 0L);
      case 23:
         return ((jjbitVec25[i2] & l2) != 0L);
      case 24:
         return ((jjbitVec26[i2] & l2) != 0L);
      case 25:
         return ((jjbitVec27[i2] & l2) != 0L);
      case 26:
         return ((jjbitVec28[i2] & l2) != 0L);
      case 27:
         return ((jjbitVec29[i2] & l2) != 0L);
      case 28:
         return ((jjbitVec30[i2] & l2) != 0L);
      case 31:
         return ((jjbitVec31[i2] & l2) != 0L);
      case 32:
         return ((jjbitVec32[i2] & l2) != 0L);
      case 33:
         return ((jjbitVec33[i2] & l2) != 0L);
      case 44:
         return ((jjbitVec34[i2] & l2) != 0L);
      case 45:
         return ((jjbitVec35[i2] & l2) != 0L);
      case 46:
         return ((jjbitVec36[i2] & l2) != 0L);
      case 48:
         return ((jjbitVec37[i2] & l2) != 0L);
      case 49:
         return ((jjbitVec38[i2] & l2) != 0L);
      case 159:
         return ((jjbitVec39[i2] & l2) != 0L);
      case 164:
         return ((jjbitVec40[i2] & l2) != 0L);
      case 166:
         return ((jjbitVec41[i2] & l2) != 0L);
      case 167:
         return ((jjbitVec42[i2] & l2) != 0L);
      case 168:
         return ((jjbitVec43[i2] & l2) != 0L);
      case 169:
         return ((jjbitVec44[i2] & l2) != 0L);
      case 170:
         return ((jjbitVec45[i2] & l2) != 0L);
      case 171:
         return ((jjbitVec46[i2] & l2) != 0L);
      case 215:
         return ((jjbitVec47[i2] & l2) != 0L);
      case 250:
         return ((jjbitVec48[i2] & l2) != 0L);
      case 251:
         return ((jjbitVec49[i2] & l2) != 0L);
      case 253:
         return ((jjbitVec50[i2] & l2) != 0L);
      case 254:
         return ((jjbitVec51[i2] & l2) != 0L);
      case 255:
         return ((jjbitVec52[i2] & l2) != 0L);
      default :
         if ((jjbitVec4[i1] & l1) != 0L)
            if ((jjbitVec5[i2] & l2) == 0L)
               return false;
            else
            return true;
         if ((jjbitVec3[i1] & l1) != 0L)
            return true;
         return false;
   }
}
private static final boolean jjCanMove_2(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec53[i2] & l2) != 0L);
      case 2:
         return ((jjbitVec7[i2] & l2) != 0L);
      case 3:
         return ((jjbitVec54[i2] & l2) != 0L);
      case 4:
         return ((jjbitVec55[i2] & l2) != 0L);
      case 5:
         return ((jjbitVec56[i2] & l2) != 0L);
      case 6:
         return ((jjbitVec57[i2] & l2) != 0L);
      case 7:
         return ((jjbitVec58[i2] & l2) != 0L);
      case 8:
         return ((jjbitVec59[i2] & l2) != 0L);
      case 9:
         return ((jjbitVec60[i2] & l2) != 0L);
      case 10:
         return ((jjbitVec61[i2] & l2) != 0L);
      case 11:
         return ((jjbitVec62[i2] & l2) != 0L);
      case 12:
         return ((jjbitVec63[i2] & l2) != 0L);
      case 13:
         return ((jjbitVec64[i2] & l2) != 0L);
      case 14:
         return ((jjbitVec65[i2] & l2) != 0L);
      case 15:
         return ((jjbitVec66[i2] & l2) != 0L);
      case 16:
         return ((jjbitVec67[i2] & l2) != 0L);
      case 18:
         return ((jjbitVec22[i2] & l2) != 0L);
      case 19:
         return ((jjbitVec68[i2] & l2) != 0L);
      case 20:
         return ((jjbitVec0[i2] & l2) != 0L);
      case 22:
         return ((jjbitVec24[i2] & l2) != 0L);
      case 23:
         return ((jjbitVec69[i2] & l2) != 0L);
      case 24:
         return ((jjbitVec70[i2] & l2) != 0L);
      case 25:
         return ((jjbitVec71[i2] & l2) != 0L);
      case 26:
         return ((jjbitVec72[i2] & l2) != 0L);
      case 27:
         return ((jjbitVec73[i2] & l2) != 0L);
      case 28:
         return ((jjbitVec74[i2] & l2) != 0L);
      case 29:
         return ((jjbitVec75[i2] & l2) != 0L);
      case 31:
         return ((jjbitVec31[i2] & l2) != 0L);
      case 32:
         return ((jjbitVec76[i2] & l2) != 0L);
      case 33:
         return ((jjbitVec33[i2] & l2) != 0L);
      case 44:
         return ((jjbitVec77[i2] & l2) != 0L);
      case 45:
         return ((jjbitVec78[i2] & l2) != 0L);
      case 46:
         return ((jjbitVec36[i2] & l2) != 0L);
      case 48:
         return ((jjbitVec79[i2] & l2) != 0L);
      case 49:
         return ((jjbitVec38[i2] & l2) != 0L);
      case 77:
         return ((jjbitVec5[i2] & l2) != 0L);
      case 159:
         return ((jjbitVec39[i2] & l2) != 0L);
      case 164:
         return ((jjbitVec40[i2] & l2) != 0L);
      case 166:
         return ((jjbitVec80[i2] & l2) != 0L);
      case 167:
         return ((jjbitVec42[i2] & l2) != 0L);
      case 168:
         return ((jjbitVec81[i2] & l2) != 0L);
      case 169:
         return ((jjbitVec82[i2] & l2) != 0L);
      case 170:
         return ((jjbitVec83[i2] & l2) != 0L);
      case 171:
         return ((jjbitVec84[i2] & l2) != 0L);
      case 215:
         return ((jjbitVec47[i2] & l2) != 0L);
      case 250:
         return ((jjbitVec48[i2] & l2) != 0L);
      case 251:
         return ((jjbitVec85[i2] & l2) != 0L);
      case 253:
         return ((jjbitVec50[i2] & l2) != 0L);
      case 254:
         return ((jjbitVec86[i2] & l2) != 0L);
      case 255:
         return ((jjbitVec87[i2] & l2) != 0L);
      default :
         if ((jjbitVec3[i1] & l1) != 0L)
            return true;
         return false;
   }
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop:
  for (;;)
  {
   try
   {
      curChar = input_stream.beginToken();
   }
   catch(final Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      CommonTokenAction(matchedToken);
      return matchedToken;
   }
   image = jjimage;
   image.setLength(0);
   jjimageLen = 0;

   for (;;)
   {
     switch(curLexState)
     {
       case 0:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_0();
         break;
       case 1:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_1();
         if (jjmatchedPos == 0 && jjmatchedKind > 12)
         {
            jjmatchedKind = 12;
         }
         break;
     }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           matchedToken.specialToken = specialToken;
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           CommonTokenAction(matchedToken);
           return matchedToken;
        }
        else if ((jjtoSkip[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
           {
              matchedToken = jjFillToken();
              if (specialToken == null)
                 specialToken = matchedToken;
              else
              {
                 matchedToken.specialToken = specialToken;
                 specialToken = (specialToken.next = matchedToken);
              }
              SkipLexicalActions(matchedToken);
           }
           else
              SkipLexicalActions(null);
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
        jjimageLen += jjmatchedPos + 1;
      if (jjnewLexState[jjmatchedKind] != -1)
        curLexState = jjnewLexState[jjmatchedKind];
        curPos = 0;
        jjmatchedKind = 0x7fffffff;
        try {
           curChar = input_stream.readChar();
           continue;
        }
        catch (final java.io.IOException e1) { }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try {
       input_stream.readChar();
       input_stream.backup(1);
     }
     catch (final java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.getImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.getImage();
     }
     throw new TokenMgrException(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrException.LEXICAL_ERROR);
   }
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public CypherPreParserTokenManager(CharStream stream){
    input_stream = stream;
  }

  /** Constructor. */
  public CypherPreParserTokenManager (CharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(CharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 12; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(CharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 2 || lexState < 0)
      throw new TokenMgrException("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrException.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
   "IN_MULTI_LINE_COMMENT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 0, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0x120ffL, 
};
static final long[] jjtoSkip = {
   0xb00L, 
};
static final long[] jjtoSpecial = {
   0xa00L, 
};
static final long[] jjtoMore = {
   0x1400L, 
};
    protected CharStream  input_stream;

    private final int[] jjrounds = new int[12];
    private final int[] jjstateSet = new int[2 * 12];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
