/* Generated by: ParserGeneratorCC: Do not edit this line. CypherPreParserConstants.java */
/*
 * Copyright (c) "Neo4j"
 * Neo4j Sweden AB [https://neo4j.com]
 *
 * This file is part of Neo4j.
 *
 * Neo4j is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.neo4j.cypher.internal.preparser.javacc;


/**
 * Token literal values and constants.
 * Generated by com.helger.pgcc.output.java.OtherFilesGenJava#start()
 */
public interface CypherPreParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EXPLAIN = 1;
  /** RegularExpression Id. */
  int PROFILE = 2;
  /** RegularExpression Id. */
  int CYPHER = 3;
  /** RegularExpression Id. */
  int VERSION = 4;
  /** RegularExpression Id. */
  int NUMBER = 5;
  /** RegularExpression Id. */
  int EQ = 6;
  /** RegularExpression Id. */
  int SLASH = 7;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 11;
  /** RegularExpression Id. */
  int IDENTIFIER = 13;
  /** RegularExpression Id. */
  int LETTER = 14;
  /** RegularExpression Id. */
  int PART_LETTER = 15;
  /** RegularExpression Id. */
  int UNKNOWN = 16;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"EXPLAIN\"",
    "\"PROFILE\"",
    "\"CYPHER\"",
    "<VERSION>",
    "<NUMBER>",
    "\"=\"",
    "\"/\"",
    "<token of kind 8>",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 12>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "<UNKNOWN>",
  };

}
